# Generated by Django 4.1.5 on 2023-01-26 20:37

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(help_text="Описание задачи", max_length=64)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Активна ли задача"),
                ),
                (
                    "timestamp_created",
                    models.DateTimeField(
                        auto_now=True, help_text="Дата создания задачи"
                    ),
                ),
                (
                    "timestamp_closed",
                    models.DateTimeField(
                        blank=True, help_text="Дата завершения задачи", null=True
                    ),
                ),
            ],
            options={"get_latest_by": "modified", "abstract": False,},
        ),
    ]
