# Generated by Django 4.1.5 on 2023-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="timestamp_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Дата создания задачи"
            ),
        ),
    ]
